//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string BrowserPagesTitle {
            get {
                return ResourceManager.GetString("BrowserPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to russia.
        /// </summary>
        internal static string DefaultTopicRussiaNewsSearchString {
            get {
                return ResourceManager.GetString("DefaultTopicRussiaNewsSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string DefaultTopicRussiaNewsText {
            get {
                return ResourceManager.GetString("DefaultTopicRussiaNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to science.
        /// </summary>
        internal static string DefaultTopicScienceSearchString {
            get {
                return ResourceManager.GetString("DefaultTopicScienceSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string DefaultTopicScienceText {
            get {
                return ResourceManager.GetString("DefaultTopicScienceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to world.
        /// </summary>
        internal static string DefaultTopicWorldNewsSearchString {
            get {
                return ResourceManager.GetString("DefaultTopicWorldNewsSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World News.
        /// </summary>
        internal static string DefaultTopicWorldNewsText {
            get {
                return ResourceManager.GetString("DefaultTopicWorldNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string DetailPageTitle {
            get {
                return ResourceManager.GetString("DetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Topic.
        /// </summary>
        internal static string EditNewsPageDeleteTopic {
            get {
                return ResourceManager.GetString("EditNewsPageDeleteTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your added topics will be displayed here.
        /// </summary>
        internal static string EditNewsPageNoItemText {
            get {
                return ResourceManager.GetString("EditNewsPageNoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reorder topics, hold down and move.
        /// </summary>
        internal static string EditNewsPageReorderText {
            get {
                return ResourceManager.GetString("EditNewsPageReorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit My News.
        /// </summary>
        internal static string EditNewsPageTitle {
            get {
                return ResourceManager.GetString("EditNewsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MasterPageLoginText {
            get {
                return ResourceManager.GetString("MasterPageLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MasterPageLogoutText {
            get {
                return ResourceManager.GetString("MasterPageLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MasterPageNoInternetCancel {
            get {
                return ResourceManager.GetString("MasterPageNoInternetCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string MasterPageNoInternetTitle {
            get {
                return ResourceManager.GetString("MasterPageNoInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, user:).
        /// </summary>
        internal static string MasterPageNoUserEmailText {
            get {
                return ResourceManager.GetString("MasterPageNoUserEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        internal static string MasterPageTitle {
            get {
                return ResourceManager.GetString("MasterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, .
        /// </summary>
        internal static string MasterPageUserEmailText {
            get {
                return ResourceManager.GetString("MasterPageUserEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string MoreTopicsBusiness {
            get {
                return ResourceManager.GetString("MoreTopicsBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string MoreTopicsEntertainment {
            get {
                return ResourceManager.GetString("MoreTopicsEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football.
        /// </summary>
        internal static string MoreTopicsFootball {
            get {
                return ResourceManager.GetString("MoreTopicsFootball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string MoreTopicsSport {
            get {
                return ResourceManager.GetString("MoreTopicsSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech.
        /// </summary>
        internal static string MoreTopicsTech {
            get {
                return ResourceManager.GetString("MoreTopicsTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news.
        /// </summary>
        internal static string NewsNoItem {
            get {
                return ResourceManager.GetString("NewsNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string NewsRepeatButton {
            get {
                return ResourceManager.GetString("NewsRepeatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search topics and articles.
        /// </summary>
        internal static string SearchPagePlaceholderText {
            get {
                return ResourceManager.GetString("SearchPagePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        internal static string TopicsContinentAfrica {
            get {
                return ResourceManager.GetString("TopicsContinentAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        internal static string TopicsContinentAsia {
            get {
                return ResourceManager.GetString("TopicsContinentAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string TopicsContinentAustralia {
            get {
                return ResourceManager.GetString("TopicsContinentAustralia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        internal static string TopicsContinentEurope {
            get {
                return ResourceManager.GetString("TopicsContinentEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        internal static string TopicsContinentNorthAmerica {
            get {
                return ResourceManager.GetString("TopicsContinentNorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SouthAmerica.
        /// </summary>
        internal static string TopicsContinentSouthAmerica {
            get {
                return ResourceManager.GetString("TopicsContinentSouthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        internal static string TopicsGroupHeaderContinent {
            get {
                return ResourceManager.GetString("TopicsGroupHeaderContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More topics.
        /// </summary>
        internal static string TopicsGroupHeaderMoreTopics {
            get {
                return ResourceManager.GetString("TopicsGroupHeaderMoreTopics", resourceCulture);
            }
        }
    }
}
